config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'update_main_home_adress', to: 'users/registrations#update_main_home_adress'
    post 'update_main_work_adress', to: 'users/registrations#update_main_work_adress'
  end
  resources :adresses
  resources :gyms
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  def index
    @adress = current_user.adresses.new
  end
  def create
    @adress = current_user.adresses.new(adress_params)
    @adress.save
    redirect_to adresses_path
  end
  private

    def adress_params
      params.require(:adress).permit(:latitude, :longitude, :kind, :name, :address)
    end
end

app/helpers/adress_helper.rb
module AdressHelper
end

app/views/adresses/_adress.html.slim
li.collection-item.transparent
  span.title
    = adress.name
  - if adress.is_home_adress?
    span.secondary-content
      = link_to "set as home adress", update_main_home_adress_path(default_home_adress: adress.id), method: :post, remote: true, id: "home-adress-link"
  - if adress.is_work_adress?
    span.secondary-content
      = link_to "set as work adress", update_main_work_adress_path(default_work_adress: adress.id), method: :post, remote: true, id: "work-adress-link"
javascript:
  $(document).ready ->
  $("#home-adress-link").on("ajax:success", (e, data, status, xhr) ->
    $("#home-title").html xhr.responseText
  $("#work-adress-link").on("ajax:success", (e, data, status, xhr) ->
    $("#work-title").html xhr.responseText

app/views/adresses/_gympass.html.slim
h2 Este es un empleado
.row
  .col.s6
    .row
      .col.s6
        - unless current_user.is_empty_integer?(current_user.default_work_adress)
          = render "adresses/work_main"
      .col.s6
        ul.collection
          = render current_user.work_adresses
  .col.s6
    = render "adresses/forms/work"

app/views/adresses/_home_main.html.slim
.card.z-depth-0
  .card-image
    = image_tag google_map(location: [current_user.main_home_adress.latitude, current_user.main_home_adress.longitude].join(','))
  .card-content
    span.card-title#home-title
      = current_user.main_home_adress.name

app/views/adresses/_manager.html.slim
h2 Este es un manager
.row
  .col.s6
    .row
      .col.s6
        - unless current_user.is_empty_integer?(current_user.default_work_adress)
          = render "adresses/work_main"
      .col.s6
        ul.collection
          = render current_user.work_adresses
  .col.s6
    = render "adresses/forms/work"

app/views/adresses/_regular.html.slim
h2 Este es un regular
.row
  .col.s6
    .row
      .col.s6
        - unless current_user.is_empty_integer?(current_user.default_home_adress)
          = render "adresses/home_main"
      .col.s6
        ul.collection
          = render current_user.home_adresses
      .col.s12
        = render "adresses/forms/home"
  .col.s6
    .row
      .col.s6
        - unless current_user.is_empty_integer?(current_user.default_work_adress)
          = render "adresses/work_main"
      .col.s6
        ul.collection
          = render current_user.work_adresses
      .col.s12
        = render "adresses/forms/work"

app/views/adresses/_work_main.html.slim
.card.z-depth-0
  .card-image
    = image_tag google_map(location: [current_user.main_work_adress.latitude, current_user.main_work_adress.longitude].join(','))
  .card-content
    span.card-title#work-title
      = current_user.main_work_adress.name

app/views/adresses/index.html.slim
.row
  .col.s12
    - if current_user.is_manager?
      = render "adresses/manager"
    - if current_user.is_regular?
      = render "adresses/regular"
    - if current_user.is_gympass?
      = render "adresses/gympass"